"""category pages added

Revision ID: 01a8473fde32
Revises: 4d60b66acd0b
Create Date: 2020-09-22 14:23:31.755283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a8473fde32'
down_revision = '4d60b66acd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('dislike', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('Like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'Like')
    op.drop_column('dislikes', 'dislike')
    # ### end Alembic commands ###
