"""pitches.html

Revision ID: 0c2ade9137bd
Revises: d04ee325876c
Create Date: 2020-09-21 11:06:46.311111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2ade9137bd'
down_revision = 'd04ee325876c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.drop_column('pitches', 'category')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    op.drop_table('categories')
    # ### end Alembic commands ###
