"""category changedh

Revision ID: 8db15e5cf9c1
Revises: 63e3f669f6f9
Create Date: 2020-09-20 16:29:00.674564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db15e5cf9c1'
down_revision = '63e3f669f6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###
